name = "thoughts"
compatibility_date = "2025-09-14"

[[redirects]]
from = "/arena"
to = "https://are.na/vlad-esafev"
status = 301

[[redirects]]
from = "/x"
to = "https://x.com/vladesafev"
status = 301

[[redirects]]
from = "/twitter"
to = "https://x.com/vladesafev"
status = 301

[[redirects]]
from = "/linkedin"
to = "https://linkedin.com/in/esafev"
status = 301

[[redirects]]
from = "/instagram"
to = "https://instagram.com/vlad.esafev"
status = 301

[[redirects]]
from = "/github"
to = "https://github.com/yourusername"
status = 301

[[redirects]]
from = "/gh"
to = "https://github.com/yourusername"
status = 301
